# https://travis-ci.org/HearthSim/hsreplaynet-i18n
sudo: false
language: python

python: "3.6"

script:
  - find . -name \*.po -execdir sh -c 'msgfmt -c "$0"' '{}' \;

notifications:
  email:
    on_failure: always
    on_success: change
