project_identifier: "hsreplaynet"
api_key_env: CROWDIN_API_KEY
base_path: ""
# base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "/en/LC_MESSAGES/django.po"
    translation: "/%two_letters_code%/LC_MESSAGES/%original_file_name%"
    language_mapping:
      two_letters_code:
        es-MX: es-mx
        pt-BR: pt-br
        zh-CN: zh-hans
        zh-TW: zh-hant
  - source: "/en/LC_MESSAGES/frontend.po"
    translation: "/%two_letters_code%/LC_MESSAGES/%original_file_name%"
    language_mapping:
      two_letters_code:
        es-MX: es-mx
        pt-BR: pt-br
        zh-CN: zh-hans
        zh-TW: zh-hant
